config/routes.rb
Rails.application.routes.draw do
  resources :todo_items
  resources :todos
  devise_for :users 

  get "/mytodos", to: "application#my_todos", as: "my_todos"
  get "/mytodos/:id/items", to: "application#my_todo_items", as: "my_todo_items"
  
  patch "/todo_item/:id/unmark", to: "application#unmark", as: "unmark_todo_item"
  patch "/todo_item/:id/mark", to: "application#mark", as: "mark_todo_item"

  root "application#index"
end

app/models/todo_item.rb
class TodoItem < ApplicationRecord

    validates :name, presence: true

    belongs_to :todo

    after_create_commit { broadcast_prepend_to "todo_items" }
    after_update_commit { broadcast_replace_to "todo_items" }
    after_destroy_commit { broadcast_remove_to "todo_items" }

end

app/controllers/todo_items_controller.rb
class TodoItemsController < ApplicationController
  before_action :set_todo_item, only: %i[ show edit update destroy ]
  before_action :authenticate_user!, only: %i[ show edit update destroy ]

  def index
    @todo_items = TodoItem.all
  end

  def show
  end

  def new
    @todo_item = TodoItem.new
  end

  def edit
    @todo = @todo_item.todo
  end

  def create
    @todo_item = TodoItem.new(todo_item_params)

    respond_to do |format|
      if @todo_item.save
        format.turbo_stream
        format.html { redirect_to my_todo_items_path(@todo_item.todo), notice: "Todo Item was successfully created." }
      else
        format.turbo_stream { render turbo_stream: turbo_stream.replace("#{helpers.dom_id(@todo_item)}_form", partial: "form", locals: { todo_item: @todo_item }) }
        format.html { render :new, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @todo_item.update(todo_item_params)
        format.html { redirect_to my_todo_items_path(@todo_item.todo), notice: "Todo Item was successfully updated." }
      else
        format.turbo_stream { render turbo_stream: turbo_stream.replace("#{helpers.dom_id(@todo_item)}_form", partial: "form", locals: { todo_item: @todo_item }) }
        format.html { render :edit, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @todo_item.destroy

    respond_to do |format|
      format.turbo_stream { render turbo_stream: turbo_stream.remove("#{helpers.dom_id(@todo_item)}") }
      format.html { redirect_to my_todo_items_path(@todo_item.todo), notice: "Todo Item was successfully destroyed." }
    end
  end
    
  private
    def set_todo_item
      @todo_item = TodoItem.find(params[:id])
    end

    def todo_item_params
      params.require(:todo_item).permit(:name, :todo_id, :done)
    end
end

app/helpers/todo_items_helper.rb
module TodoItemsHelper
end

app/views/todo_items/_form.html.erb
  <%= form_with(model: todo_item, id: "#{dom_id(todo_item)}_form") do |form| %>
    <div>
      <%= form.label :name %>
      <%= form.text_field :name, class:"form-control" %>
    </div>

    <div>
      <%= form.hidden_field :todo_id, value: @todo.id %>
    </div>

    <div>
      <%= form.hidden_field :done, value: 0 %>
    </div>

    <div class="d-flex justify-content-between">
      <%= form.submit class:"btn btn-primary m-1" %>
      <%= link_to "Cancel", todo_item, class:"m-1" %>
    </div>
  <% end %> 

app/views/todo_items/_todo_item.html.erb
<div id="<%= "#{dom_id(todo_item)}" %>" class="card m-4 p-2">
  <%= turbo_frame_tag dom_id(todo_item) do %>
    <div class="d-flex justify-content-between">
      <%  if todo_item.done == 1 %>
        <div class="text-success">
      <% else %>
        <div class="text-danger">
      <% end %>
        <strong>Name:</strong>
        <%= todo_item.name %>
      </div>

      <div class="d-flex">
        <% if todo_item.done == 0 %>
          <%= button_to "Mark", mark_todo_item_path(id: todo_item.id), method: :patch, class:"btn btn-success m-1" %>
        <% else %>
          <%= button_to "UnMark", unmark_todo_item_path(id: todo_item.id),method: :patch, class:"btn btn-danger m-1" %>
        <% end %>
        <%= link_to "Edit", edit_todo_item_path(todo_item), class:"btn btn-warning m-1" %>
        <%= button_to "Delete", todo_item, method: :delete, data: { turbo_confirm: 'Are you sure?' }, class:"btn btn-danger m-1" %>
      </div>
    </div>
  <% end %>
</div>  

app/views/todo_items/edit.html.erb
<%= turbo_frame_tag dom_id(@todo_item) do %>
  <%= render "form", todo_item: @todo_item %>
<% end %>
<br>

app/views/todo_items/index.html.erb
<div class="mx-auto mt-4">
  <div class="mb-6">
    <h1 class="font-bold">Todo Items</h1>
  </div>

  <%= turbo_stream_from "todo_items" %>
  <div id="todo_items" class="m-2">
    <%= render @todo_items %>
  </div>
</div>

app/views/todo_items/new.html.erb
<div class="m-2 p-2">
  <h1>New todo item</h1>

  <%= render "form", todo_item: @todo_item %>

  <br>

  <div>
    <%= link_to "Back to todo items", my_todo_items_path(id: @todo_item.todo_id), class:"btn btn-primary m-1" %>
  </div>
</div>

app/views/todo_items/show.html.erb
<div class="m-2 p-2">
  <%= render @todo_item %>

  <div>
    <%= link_to "Edit this todo item", edit_todo_item_path(@todo_item), class:"btn btn-warning m-1" %> |
    <%= link_to "Back to todo items", todo_items_path, class:"btn btn-primary m-1" %>

    <%= button_to "Destroy this todo item", @todo_item, method: :delete, data: { turbo_confirm: 'Are you sure?' }, class:"btn btn-danger m-1" %>
  </div>
</div>