config/routes.rb
Rails.application.routes.draw do
  resources :todo_items
  resources :todos
  devise_for :users 

  get "/mytodos", to: "application#my_todos", as: "my_todos"
  get "/mytodos/:id/items", to: "application#my_todo_items", as: "my_todo_items"
  
  patch "/todo_item/:id/unmark", to: "application#unmark", as: "unmark_todo_item"
  patch "/todo_item/:id/mark", to: "application#mark", as: "mark_todo_item"

  root "application#index"
end

app/models/todo.rb
class Todo < ApplicationRecord

    validates :name, presence: true

    belongs_to :user
    has_many :todo_items

    after_create_commit { broadcast_prepend_to "todos" }
    after_update_commit { broadcast_replace_to "todos" }
    after_destroy_commit { broadcast_remove_to "todos" }

end

app/controllers/todos_controller.rb
class TodosController < ApplicationController
  before_action :set_todo, only: %i[ show edit update destroy ]
  before_action :authenticate_user!, only: %i[ show edit update destroy ]

  def index
    @todos = Todo.all
  end

  def show
  end

  def new
    @todo = Todo.new
  end

  def edit
  end

  def create
    @todo = Todo.new(todo_params)

    respond_to do |format|
      if @todo.save
        format.turbo_stream
        format.html { redirect_to my_todos_path(), notice: "Todo was successfully created." }
      else
        format.turbo_stream { render turbo_stream: turbo_stream.replace("#{helpers.dom_id(@todo)}_form", partial: "form", locals: { todo: @todo }) }
        format.html { render :new, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @todo.update(todo_params)
        format.html { redirect_to my_todos_path(), notice: "Todo was successfully updated." }
      else
        format.turbo_stream { render turbo_stream: turbo_stream.replace("#{helpers.dom_id(@todo)}_form", partial: "form", locals: { todo: @todo }) }
        format.html { render :edit, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @todo.destroy

    respond_to do |format|
      format.turbo_stream { render turbo_stream: turbo_stream.remove("#{helpers.dom_id(@todo)}") }
      format.html { redirect_to my_todos_path, notice: "Todo was successfully destroyed." }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_todo
      @todo = Todo.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def todo_params
      params.require(:todo).permit(:name, :user_id)
    end
end

app/helpers/todos_helper.rb
module TodosHelper
end

app/views/todos/_form.html.erb
<div class="m-4">
  <%= form_with(model: todo, id: "#{dom_id(todo)}_form") do |form| %>
    <div>
      <%= form.label :name %>
      <%= form.text_field :name, class:"form-control" %>
    </div>

    <div>
      <%= form.hidden_field :user_id, value:current_user.id %>
    </div>
    <br>
    <div>
      <%= form.submit class:"btn btn-primary"%>
    </div>
  <% end %>
</div>

app/views/todos/_todo.html.erb
<div id="<%= "#{dom_id(todo)}" %>">
  <%= turbo_frame_tag dom_id(todo) do %>
    <div class="card m-4 p-4">
      <div id="<%= dom_id todo %>" class="d-flex justify-content-between">
        <div>
          <strong>Name:</strong>
          <%= link_to todo.name, my_todo_items_path(todo), class: "text-black text-decoration-none" %>
        </div>

        <div class="d-flex">
          <%= link_to "Edit", edit_todo_path(todo), class:"btn btn-warning m-1" %>
          <%= button_to "Delete", todo, method: :delete, data: { turbo_confirm: 'Are you sure?' }, class:"btn btn-danger m-1" %>
        </div>
    </div>
  <% end %>
</div>

app/views/todos/create.turbo_stream.erb
<%= turbo_stream.prepend "todos" do %>
  <%= render "todo", todo: @todo %>
<% end %>
<%= turbo_stream.replace "#{dom_id(Todo.new)}_form" do %>
  <%= render "form", todo: Todo.new %>
<% end %>

app/views/todos/edit.html.erb
<%= turbo_frame_tag dom_id(@todo) do %>
  <%= render "form", todo: @todo %>
<% end %>
<br>

app/views/todos/index.html.erb
<div class="mx-auto mt-4">
  <div class="mb-6">
    <h1 class="font-bold">Todo</h1>
  </div>

  <%= render "form", todo: Todo.new %>

  <%= turbo_stream_from "todos" %>
  <div id="todos" class="m-2">
    <%= render @todos %>
  </div>
</div>

app/views/todos/new.html.erb
<div class="m-2 p-2">
  <h1>New todo</h1>

  <%= render "form", todo: @todo %>

  <br>

  <div>
    <%= link_to "Back to todos", my_todos_path, class:"btn btn-primary m-1" %>
  </div>
</div>

app/views/todos/show.html.erb
<div class="m-2 p-2">
  <%= render @todo %>
  <div>
    <%= link_to "Edit this todo", edit_todo_path(@todo), class:"btn btn-warning m-1" %> |
    <%= link_to "Back to todos", my_todos_path, class:"btn btn-primary m-1" %>

    <%= button_to "Destroy this todo", @todo, method: :delete, data: { turbo_confirm: 'Are you sure?' }, class:"btn btn-danger m-1" %>
  </div>
</div>