config/routes.rb
Rails.application.routes.draw do
  resources :todo_items
  resources :todos
  devise_for :users 

  get "/mytodos", to: "application#my_todos", as: "my_todos"
  get "/mytodos/:id/items", to: "application#my_todo_items", as: "my_todo_items"
  
  patch "/todo_item/:id/unmark", to: "application#unmark", as: "unmark_todo_item"
  patch "/todo_item/:id/mark", to: "application#mark", as: "mark_todo_item"

  root "application#index"
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    before_action :authenticate_user!, only: %i[ my_todos my_todo_items mark unmark ]

    def index
    end
   
    def my_todos
        @todo = Todo.new
    end
    
    def my_todo_items
        @todo = Todo.find(params[:id])
        @todo_item = TodoItem.new
        @x = @todo.todo_items.where(done: 1).count
        @y = @todo.todo_items.count
    end

    def mark
        @todo_item1 = TodoItem.find(params[:id])
        @todo_item1.done = 1
        
        respond_to do |format|
            if @todo_item1.save
                format.turbo_stream { render turbo_stream: turbo_stream.replace("bar", partial: "layouts/bar", locals: { x: @todo_item1.todo.todo_items.where(done: 1).count, y: @todo_item1.todo.todo_items.count }) }
                format.html { redirect_to my_todo_items_path(@todo_item1.todo), success: "Done." }
            end
        end
    end
    
    def unmark
        @todo_item1 = TodoItem.find(params[:id])
        @todo_item1.done = 0
        respond_to do |format|
            if @todo_item1.save
                format.turbo_stream { render turbo_stream: turbo_stream.replace("bar", partial: "layouts/bar", locals: { x: @todo_item1.todo.todo_items.where(done: 1).count, y: @todo_item1.todo.todo_items.count }) }
                format.html { redirect_to my_todo_items_path(@todo_item1.todo), success: "Undone." }
            end
        end
    end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/application/index.html.erb
<div class="m-5 p-5 bg-secondary text-center">
    <% if user_signed_in? %>
        Welcome <%= current_user.email %> to TODO App <br>
        Let's get started <%= link_to "TODOS", my_todos_path, class:"btn btn-primary m-1" %> 
    <% else %>
        Please Sign in to use our app.<br>
        ( email: test@test.com password:qwe123 ) for testing<br>
        <%= link_to "Login", new_user_session_path, class:"btn btn-primary m-1" %> or
        <%= link_to "Register", new_user_registration_path, class:"btn btn-primary m-1" %>
    <% end %>
</div>

app/views/application/my_todo_items.html.erb
<div class="m-4 p-4 card">
    <div class="card-header p-4 d-flex justify-content-between">
        <h2><%= @todo.name %></h2>
        <%= link_to "Back", my_todos_path, class:"btn btn-secondary m-1" %>
    </div>
    
    <br>
    <%= turbo_frame_tag "todo_item_form" do %>
        <%= render "todo_items/form", todo_item: @todo_item, todo: @todo %>
    <% end %>
    <br>

    <% if @todo.todo_items.count != 0 %>
       <%= render "layouts/bar", x: @x, y: @y %>
    <% end %>
    
    <div id="my_todos_items">
        <%= turbo_stream_from "todo_items" %>
        <%= turbo_frame_tag "todo_items" do %>
            <% @todo.todo_items.each do |todo_item| %>
                <%= render todo_item %>
            <% end %>
        <% end %>     
    </div>
</div>

app/views/application/my_todos.html.erb
<div class="m-4 p-4 card">
    <div class="card-header p-4 d-flex justify-content-between">
        <h2>My TODO List</h2>
    </div>

   
    <%= turbo_frame_tag "todo_form" do %>
        <%= render "todos/form" ,todo: @todo %>
    <% end %>

    <div id="my_todos">
        <%= turbo_stream_from "todos" %>
        <%= turbo_frame_tag "todos" do %>
            <% current_user.todos.each do |todo| %>
                <%= render todo %>
            <% end %>
        <% end %>    
    </div>
</div>